name: Generate Fancy Game List

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyGithub requests jinja2

      - name: Generate index.html
        env:
          GH_TOKEN: ${{ secrets.MY_GH_TOKEN }}
        run: python scripts/generate_index.py
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          path: ./_site
